#!/bin/bash
#Script Mod by Cyberperu DEMS Hack-peru
figlet -cf slant "Welcome" | lolcat
figlet -cf slant "Cyberperu" | lolcat
echo -e "    #====================================================================#" | lolcat
echo -e "    #                  Premium Script By Cyberperu                    #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #         ░█▀▀▀█ ░█▄─░█ ░█▀▀▀ 　 ░█▀▀█ ▀█▀ ░█▀▀▀ ░█▀▀█ ░█▀▀▀         #" | lolcat
echo -e "    #         ░█──░█ ░█░█░█ ░█▀▀▀ 　 ░█▄▄█ ░█─ ░█▀▀▀ ░█─── ░█▀▀▀         #" | lolcat
echo -e "    #         ░█▄▄▄█ ░█──▀█ ░█▄▄▄ 　 ░█─── ▄█▄ ░█▄▄▄ ░█▄▄█ ░█▄▄▄         #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #                        - Modded By : Cyberperu                  #" | lolcat
echo -e "    #          │▒│  /▒/      - Thanks To : Hack-peru                      #" | lolcat
echo -e "    #          │▒│ /▒/       - Whatsapp  : *********                     #" | lolcat
echo -e "    #          │▒|/▒/┬─┐     - Telegram  : t.me/CYBERPERU_P            #" | lolcat
echo -e "    #          │▒│▒|▒│▒│     - For those who use this script,            #" | lolcat
echo -e "    #         ┌┴─┴─┐-┘─┘       this script is still under development    #" | lolcat
echo -e "    #         │▒┌──┘▒▒▒│     - Thanks for who using this script          #" | lolcat
echo -e "    #         └┐▒▒▒▒▒▒┌┘     - To EnterMenuList = 'menu'                 #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #====================================================================#" | lolcat
echo -e " "
echo -e "                             \e[1;32mPowered By Cyberperu\e[0m"
echo -e "                       \e[1;32m\e[1;32mCOPYRIGHT © 2022 Cyberperu Newbie\e[0m"
echo -e "                \e[1;32mPrivacy Policy Terms & Conditions Disclaimer\e[0m"
